### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by chiru125** [mdrhmn/tweets_extractor#1]
Hi I found this code very helpful for on of my project !

I was getting **module not found**(Tried different methods to install but was unsuccessful!) error while authenticating the credentials using dotenv/env.py. 

Hence I used **config method** to authenticate (saved the credentials in a file called config.py).

I am getting the error as shown in attached screen shot ..
![Authentication error](https://user-images.githubusercontent.com/100480914/155872797-1bbe8306-65b7-4102-a1ed-b2dd446dc38e.PNG)

Secondly: Is there a way to mention date range to pull tweets rather than specifying the number of tweets to pull?

appreciate your quick response on this 

Thank you so much !

**Comment by mdrhmn** [comment]
> Hi I found this code very helpful for on of my project !
> 
> I was getting **module not found**(Tried different methods to install but was unsuccessful!) error while authenticating the credentials using dotenv/env.py.
> 
> Hence I used **config method** to authenticate (saved the credentials in a file called config.py).
> 
> I am getting the error as shown in attached screen shot .. ![Authentication error](https://user-images.githubusercontent.com/100480914/155872797-1bbe8306-65b7-4102-a1ed-b2dd446dc38e.PNG)
> 
> Secondly: Is there a way to mention date range to pull tweets rather than specifying the number of tweets to pull?
> 
> appreciate your quick response on this
> 
> Thank you so much !

For the first question, have you installed the required package using pip? https://pypi.org/project/python-decouple/ 

And for the second question, the [user_timeline](https://docs.tweepy.org/en/stable/api.html#tweepy.API.user_timeline) method does not support `since` and `until` date parameters (and user timelines are limited to the most recent 3200 Tweets posted)**. Also, the API has been updated constantly, so maybe you can refer to this [StackOverflow post](https://stackoverflow.com/questions/66342854/how-to-analyse-tweets-within-date-constraints) for more info.

Hope that helps and apologies for the late reply!

**Comment by mdrhmn** [comment]
> Hi I found this code very helpful for on of my project !
> 
> I was getting **module not found**(Tried different methods to install but was unsuccessful!) error while authenticating the credentials using dotenv/env.py.
> 
> Hence I used **config method** to authenticate (saved the credentials in a file called config.py).
> 
> I am getting the error as shown in attached screen shot .. ![Authentication error](https://user-images.githubusercontent.com/100480914/155872797-1bbe8306-65b7-4102-a1ed-b2dd446dc38e.PNG)
> 
> Secondly: Is there a way to mention date range to pull tweets rather than specifying the number of tweets to pull?
> 
> appreciate your quick response on this
> 
> Thank you so much !

For the first question, have you installed the required package using pip? https://pypi.org/project/python-decouple/ 

And for the second question, the [user_timeline](https://docs.tweepy.org/en/stable/api.html#tweepy.API.user_timeline) method does not support `since` and `until` date parameters (and user timelines are limited to the most recent 3200 Tweets posted). Also, the API has been updated constantly, so maybe you can refer to this [StackOverflow post](https://stackoverflow.com/questions/66342854/how-to-analyse-tweets-within-date-constraints) for more info.

Hope that helps and apologies for the late reply!

**Comment by chiru125** [comment]
Hi @mdrhmn. Yes I have installed all the package mentioned in the code and I am still getting the same error(NameError: name 'config' is not defined)... 

Am I missing something ? . Can you please assist on this?

**Comment by mdrhmn** [comment]
> Hi @mdrhmn. Yes I have installed all the package mentioned in the code and I am still getting the same error(NameError: name 'config' is not defined)...
> 
> Am I missing something ? . Can you please assist on this?

Are you using a virtual environment in your project? If you run the command `pip freeze`, do the list of Python packages that you installed can be seen?

**Comment by chiru125** [comment]
Hello @mdrhmn Thank you for responding back... Not very sure about virtual environment. But when i run `pip freeze` I see all the packages I installed ... Is there direct way of authenticating credentials and run the entire code ? I have seen many similar codes which authenticate twitter credentials and pull the tweets(single user). However, I am unsure about using it in the above code.

Thanks again for looking into it !

**Comment by mdrhmn** [comment]
> Hello @mdrhmn Thank you for responding back... Not very sure about virtual environment. But when i run `pip freeze` I see all the packages I installed ... Is there direct way of authenticating credentials and run the entire code ? I have seen many similar codes which authenticate twitter credentials and pull the tweets(single user). However, I am unsure about using it in the above code.
> 
> Thanks again for looking into it !

Yes, you can actually directly paste the API credentials instead of using `config`, provided you do not push the code in any public repositories (hence why I coded mine using environment variables which is the best practice). You can refer to the following example, where you simply replace `'CONSUMER_KEY'` with the string value of your API keys.

`
consumer_key = 'CONSUMER_KEY'...
`

Also out of curiosity, have you tried using the dotenv method as an alternative?
